name: enstack
description: The project enabling endeavors
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  retrofit: ^2.0.0
  rxdart: ^0.27.1
  equatable: ^2.0.3
  pedantic: ^1.11.1
  cupertino_icons: ^1.0.2
  logging: ^1.0.1
  shared_preferences: ^2.0.6
  intl: ^0.17.0
  get_it: ^7.1.3
  get: ^4.1.4
  validators: ^3.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0

dev_dependencies:
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  mockito: ^5.0.10
  bloc_test: ^8.0.0
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_intl:
  enabled: true
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en

  localizely: # Optional settings if you use Localizely platform. Read more: https://localizely.com/flutter-localization-workflow
    project_id: # Configured manually or through 'Connect to Localizely' command. Get it from the https://app.localizely.com/projects page.
    upload_overwrite: # Set to true if you want to overwrite translations with upload. Default: false
    upload_as_reviewed: # Set to true if you want to mark uploaded translations as reviewed. Default: false
    ota_enabled: # Set to true if you want to use Localizely Over-the-air functionality. Default: false